### ISSUE TITLE
not support go1.N.0 version format

### ISSUE THREAD

**Issue by shenghuang147** [openSUSE/obs-service-go_modules#33]
According to https://tip.golang.org/doc/go1.21:

Go 1.21 introduces a small change to the numbering of releases. In the past, we used Go 1.N to refer to both the overall Go language version and release family as well as the first release in that family. Starting in Go 1.21, the first release is now Go 1.N.0. Today we are releasing both the Go 1.21 language and its initial implementation, the Go 1.21.0 release. These notes refer to “Go 1.21”; tools like go version will report “go1. 21.0” (until you upgrade to Go 1.21.1). See “Go versions” in the “[Go Toolchains](https://tip.golang.org/doc/toolchain#version)” documentation for details about the new version numbering.

This means that obs-service-go_modules needs to adapt to this change, otherwise it can not be able to correctly identify or process the application source code of Go 1.N.0

**Comment by shenghuang147** [comment]
I am not sure if this is the right place to report the issue, so I reported it both here and in Bugzilla.

**Comment by johanneskastl** [comment]
Hit this with syft and grype:
https://github.com/anchore/syft/blob/main/go.mod#L3
https://github.com/anchore/grype/blob/main/go.mod#L3

Would be nice if this could be fixed quickly... :-)

**Comment by johanneskastl** [comment]
This can be solved by installing go1.21. I opened an SR to add this as a runtime dependency:
https://build.opensuse.org/request/show/1116159

**Comment by jfkw** [comment]
Thanks @johanneskastl and @shenghuang147 for reporting and the fix to `BuildRequires: golang(API) >= go1.21` in packaging. This has been submitted to Factory and should be available soon.

The new behaviour of `go mod init` to require the three digit version of the go toolchain used to run the command is surprising and unfortunate.  The two digit version would be more appropriate IMO. I anticipate it will cause ongoing difficulties for build environments including most Linux distributions which cannot use the upstream binary toolchain builds but may not be able to deploy packages of the latest go toolchain version immediately for all build targets.

**Comment by jfkw** [comment]
> I am not sure if this is the right place to report the issue, so I reported it both here and in Bugzilla.
> 
> https://bugzilla.opensuse.org/show_bug.cgi?id=1214933

Thanks. The best method is to file the issue at this GitHub project.
