### ISSUE TITLE
Please Update go version to 1.22

### ISSUE THREAD

**Issue by shenghuang147** [openSUSE/obs-service-go_modules#49]
> go: go.mod requires go >= 1.22 (running go 1.21.10; GOTOOLCHAIN=local) 

Please update the version of `Requires: golang(API) >= 1.21` in **obs-service-gomodules.spec** to 1.22, so that obs-service-gomodules can handle go.mod that includes 1.22 / 1.22.x.

**Comment by jfkw** [comment]
Thanks for reporting. Fixed in SR https://build.opensuse.org/request/show/1183515. Package update is making its way to openSUSE:Factory.
