### ISSUE TITLE
Please add support for xz-compressed tarballs

### ISSUE THREAD

**Issue by glaubitz** [openSUSE/obs-service-go_modules#5]
When choosing ```xz``` compression in the ```_service``` file, the service run fails with:

```
glaubitz@suse-laptop:~/suse/home:glaubitz:branches:devel:languages:go/golang-org-x-net> osc service disabledrun
Already up to date.
ef20fe5d793301b553005db740f730d87993f778
INFO:obs-service-go_modules:Using archive net-1.14+git20191126.ef20fe5.tar.xz
INFO:obs-service-go_modules:Running OBS Source Service: obs-service-go_modules
INFO:obs-service-go_modules:Extracting net-1.14+git20191126.ef20fe5.tar.xz to /home/glaubitz/suse/home:glaubitz:branches:devel:languages:go/golang-org-x-net/tmpl0seg1oi.go_modules.service
INFO:obs-service-go_modules:Unsupported archive file format for net-1.14+git20191126.ef20fe5.tar.xz
Aborting: service call failed:  /usr/lib/obs/service/go_modules --archive net-1.14+git20191126.ef20fe5.tar.xz --outdir /home/glaubitz/suse/home:glaubitz:branches:devel:languages:go/golang-org-x-net/tmpl0seg1oi.go_modules.service
glaubitz@suse-laptop:~/suse/home:glaubitz:branches:devel:languages:go/golang-org-x-net>
```

Could xz support be added in the future to resolve this?

**Comment by ismail** [comment]
This is already in but no release is tagged, can you please tag a 0.4.0 release?

**Comment by jfkw** [comment]
Yes, I'll tag a release with this. I think it would be better to have just one supported `vendor.tar.xz` compression format and remove the configuration knob now, or deprecate for removal ASAP. For existing packages, the service would update the `Source:` line from vendor.tar.gz to `vendor.tar.xz`, and there would be a one-time transition task to delete the obsolete vendor.tar.gz from an OBS project. Do you foresee any OBS or maintainer objections to xz compression as both default and only option?

**Comment by ismail** [comment]
@jfkw xz needs a BuildRequires for SLE11 but I don't think it's a problem for anyone.

**Comment by glaubitz** [comment]
Why only support xz compression? If you drop gzip support now, a lot of packages will need additional manual work when they are updated the next time.

I don't see any particular advantage in forcing to use a particular compression format.

**Comment by jfkw** [comment]
@glaubitz Very true, there are existing packages and imposition on their maintainers to consider. I'm willing to create SRs for all affected packages I can identify.

My motivation is to normalize usage to a single entry  `<service name="go_modules" mode="disabled">` in `_service`. If XZ compression is preferred for OBS (the compression ratios on text sources do seem markedly better), let's use that everywhere. I'm not opposed to supporting multiple compression formats, but would like to get the default right, which may require a correction now, while the number of dependent packages is relatively small.

@ismail, from your POV should we also eventually support `vendor.obscpio` archives? That would be an argument in favor of keeping a vendor compression/format config option.

The transition proposal would be for `obs-service-go_modules` to rewrite the .spec line `SourceN: vendor.tar.<compression>` in favor of the new default, and deprecate/ignore the compression directive with a deprecation notice in output. The maintainer would need to review a change in the `.spec` and an `osc rm vendor.tar.gz` `osc add vendor.tar.xz` before comitting. AFAICT, today all users of `obs-service-go_modules` manually run `osc service disabled run` and commit changes. In my own packaging, I always pair with setversion and others that do update the `.spec` file.

**Comment by ismail** [comment]
If it's not too much work on your side, I'd go with xz as default but configurable compression. For example, one could want zstd or some new stuff in next 10 years.

**Comment by jfkw** [comment]
Agreed, will keep configurable compression as an option and switch to a new default of xz.

**Comment by ismail** [comment]
> Agreed, will keep configurable compression as an option and switch to a new default of xz.

Any update on this? Do you rather want a pull request? :)

**Comment by jfkw** [comment]
No update as yet. I was working on a priority project in an unrelated area which is wrapping up presently. I wanted to be available to make the bulk SRs for the change of default if we go this route, and get in touch with more project maintainers ahead of the event.

To better communicate the rationale for change of default to users, is there an OBS policy or other announcement preferring .xz compression to conserve OBS resources that I can reference? I didn't see anything pertinent at https://en.opensuse.org/openSUSE:Packaging_guidelines

Using just one example,  the space savings with go sources are potentially significant:

Compression | Size  
----------- | ----
vendor.tar    | 35.0M 
vendor.tar.gz |  5.0M 
vendor.tar.xz |  2.9M 

> xz needs a BuildRequires for SLE11 but I don't think it's a problem for anyone.

If there was a call to build go1.x SLE_11_SP4, Is there a way to require xz tools at a prjconf level conditional on suse_version? If the need arose, obs-service-go_modules could insert a conditional BuildRequires.

**Comment by ismail** [comment]
One can probably do prjconf magic (Support: etc) but I believe that's nothing we should be worrying about since it's a known corner case.

About the communication, I don't know any preference for compression algorithms in OBS. But xz is ubiquitous, comparing with zstd would be interesting though.

**Comment by johanneskastl** [comment]
Any news on this? There is still not tag for the changes in master...

**Comment by dannysauer** [comment]
Well, for whoever stumbles across this trying to figure out why the module still hasn't made a decision...  Here's what I'm doing as a workaround for now - just creating another .tar.gz (so detection will find the source tarball, which is xz compressed) and then recompressing the emitted vendor.tar.gz to vendor.tar.xz.  I feel like a parameter would be a whole lot cleaner, but the world is what it is.

```xml
  <!-- go_modules only supports .tar.gz, not .obscpio or .tar.xz :facepalm: -->
  <service name="tar" mode="localonly"/>
  <service name="recompress" mode="localonly">
    <param name="file">*.tar</param>
    <param name="compression">gz</param>
  </service>
  <service name="go_modules" mode="localonly" />
  <service name="recompress" mode="localonly">
    <param name="file">vendor.tar.gz</param>
    <param name="compression">xz</param>
  </service>
```

**Comment by johanneskastl** [comment]
> This is already in but no release is tagged, @jfkw can you please tag a 0.4.0 release?

@jfkw Can we please have a new tag including the support for other compression format?

**Comment by jfkw** [comment]
Additional compression formats are supported in the `v0.4.1` release. As of the `v0.5.0` release archive read and write is via `libarchive` wrapper `python3-libarchive-c`. Compression formats supported by `obs-service-go_modules` are `gz`, `xz`, `zsdt` and `.obscpio` (`cpio_newc`).
